global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'streamer'
    static_configs:
      - targets: ['172.17.0.1:9113']  # Update this if using an exporter
  - job_name: 'rtmp_exporter'
    static_configs:
      - targets: ['172.17.0.1:8000']
  - job_name: 'rtmp_exporter_1'
    static_configs:
      - targets: ['172.17.0.1:8001']
